### ISSUE TITLE
Import name - not found

### ISSUE THREAD

**Issue by bukharidxb** [mertyyanik/pyleargist-python3#1]
Hello,
I tried to install the library in Google Colab but unfortunately, the import name doesn't work. I tried many name such import pyleargist, lear_gist, leargist etc but no luck.

I checked the install package and it shows pyleargist==2.0.5

when I tried with import lear_gist, it works but doesn't shows any function with dir(lear_gist)

Thank you

**Comment by mertyyanik** [comment]
I did not try it via google colab. You can try in tensorflow docker image.
